# Generated by Django 4.2.4 on 2023-08-09 20:58
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "change_interval_ms",
                    models.PositiveIntegerField(
                        default=5000,
                        verbose_name="Time in milliseconds image will be visible before changing.",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="main/carousel/images/",
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
            ],
        ),
    ]
