# Generated by Django 4.2.4 on 2023-10-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "change_interval_ms",
                    models.PositiveIntegerField(
                        default=5000, verbose_name="Change time (milliseconds)."
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="main/carousel/images/"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "precedence_index",
                    models.IntegerField(
                        default=0,
                        verbose_name="Index defining precedence of this image.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "footer_copyright",
                    models.CharField(
                        blank=True, default="© 2023 Makatawi", max_length=100
                    ),
                ),
                (
                    "contact_phone_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "contact_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "contact_facebook_url",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "contact_instagram_url",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "contact_youtube_url",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "contact_address_for_correspondence",
                    models.CharField(blank=True, default="", max_length=1500),
                ),
            ],
        ),
    ]
