# Generated by Django 4.2.4 on 2023-08-09 21:17
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="index",
            field=models.IntegerField(
                default=0,
                verbose_name="Index defining precedence of this image.",
            ),
        ),
        migrations.AlterField(
            model_name="carouselimage",
            name="change_interval_ms",
            field=models.PositiveIntegerField(
                default=5000,
                verbose_name="Change time (milliseconds).",
            ),
        ),
    ]
