# Generated by Django 4.2.4 on 2023-10-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=500),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("surname", models.TextField(blank=True)),
                ("phone_number", models.TextField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "square_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/square_image/"
                    ),
                ),
                (
                    "wide_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/wide_image/"
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("is_stock_public", models.BooleanField(default=False)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("is_public", models.BooleanField(default=False)),
                ("is_ordering_enabled", models.BooleanField(default=False)),
                (
                    "index",
                    models.IntegerField(
                        default=0, verbose_name="Index defining ordering of products"
                    ),
                ),
                (
                    "price_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placed_date", models.DateTimeField(auto_now_add=True)),
                ("expected_finalization_date", models.DateTimeField()),
                ("finalization_date", models.DateTimeField()),
                ("comment", models.TextField(blank=True, default="")),
                ("is_finalized", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.customerinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=500),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "price_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.currency",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.transaction",
                    ),
                ),
                (
                    "unit_of_quantity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.unit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="unit_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.unit",
            ),
        ),
    ]
