# Generated by Django 4.2.4 on 2023-10-20 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="CustomerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("surname", models.TextField(blank=True)),
                ("phone_number", models.TextField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_code", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_product_public", models.BooleanField(default=False)),
                (
                    "precedence_index",
                    models.IntegerField(
                        default=0, verbose_name="Index defining ordering of products"
                    ),
                ),
                ("stock_in_quantity_units", models.PositiveIntegerField(default=0)),
                ("is_stock_public", models.BooleanField(default=False)),
                (
                    "price_of_one_unit",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("is_price_public", models.BooleanField(default=False)),
                ("is_ordering_enabled", models.BooleanField(default=False)),
                ("expected_delivery_time", models.TextField(default="3 tygodnie")),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("category_image_alt", models.TextField(blank=True, default="")),
                (
                    "category_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/product_category/category_image/upload/",
                    ),
                ),
                (
                    "precedence_index",
                    models.IntegerField(
                        default=0, verbose_name="Index defining ordering of products"
                    ),
                ),
                ("is_public_category", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Product categories",
            },
        ),
        migrations.CreateModel(
            name="QuantityUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=500),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placed_date", models.DateTimeField(auto_now_add=True)),
                ("expected_finalization_date", models.DateTimeField()),
                ("finalization_date", models.DateTimeField()),
                ("comment", models.TextField(blank=True, default="")),
                ("is_finalized", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.customerinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "price_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.currency",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.transaction",
                    ),
                ),
                (
                    "unit_of_quantity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.quantityunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("alt", models.CharField(max_length=255)),
                (
                    "precedence_index",
                    models.IntegerField(
                        default=0, verbose_name="Index defining ordering of products"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/product_photo/image/upload/",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(to="products.productcategory"),
        ),
        migrations.AddField(
            model_name="product",
            name="price_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.currency",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity_units",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.quantityunit",
            ),
        ),
    ]
